# Generated by Django 5.2.4 on 2025-09-02 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='代理名称')),
                ('description', models.TextField(blank=True, verbose_name='代理描述')),
                ('agent_type', models.CharField(choices=[('react', 'ReAct代理'), ('openai_functions', 'OpenAI函数代理'), ('structured_chat', '结构化聊天代理'), ('conversational', '对话代理'), ('zero_shot', '零样本代理')], default='react', max_length=50, verbose_name='代理类型')),
                ('system_prompt', models.TextField(default='你是一个智能助手，可以使用各种工具来帮助用户完成任务。', verbose_name='系统提示词')),
                ('llm_model', models.CharField(default='qwen-turbo', max_length=100, verbose_name='LLM模型')),
                ('temperature', models.FloatField(default=0.7, verbose_name='温度参数')),
                ('max_tokens', models.IntegerField(default=2000, verbose_name='最大令牌数')),
                ('available_tools', models.JSONField(blank=True, default=list, verbose_name='可用工具列表')),
                ('tool_config', models.JSONField(blank=True, default=dict, verbose_name='工具配置')),
                ('memory_type', models.CharField(default='buffer_window', max_length=50, verbose_name='记忆类型')),
                ('memory_config', models.JSONField(blank=True, default=dict, verbose_name='记忆配置')),
                ('status', models.CharField(choices=[('active', '激活'), ('inactive', '停用'), ('error', '错误')], default='active', max_length=20, verbose_name='状态')),
                ('user_id', models.IntegerField(verbose_name='创建者ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execution_count', models.IntegerField(default=0, verbose_name='执行次数')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
            ],
            options={
                'verbose_name': '智能代理',
                'verbose_name_plural': '智能代理',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.UUIDField(verbose_name='代理ID')),
                ('conversation_id', models.IntegerField(blank=True, null=True, verbose_name='对话ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('agent_output', models.TextField(blank=True, verbose_name='代理输出')),
                ('execution_steps', models.JSONField(blank=True, default=list, verbose_name='执行步骤')),
                ('tools_used', models.JSONField(blank=True, default=list, verbose_name='使用的工具')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='running', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(秒)')),
                ('token_usage', models.JSONField(blank=True, default=dict, verbose_name='令牌使用量')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '代理执行记录',
                'verbose_name_plural': '代理执行记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='工具名称')),
                ('description', models.TextField(verbose_name='工具描述')),
                ('tool_type', models.CharField(choices=[('document_search', '文档搜索'), ('web_search', '网络搜索'), ('calculator', '计算器'), ('python_repl', 'Python执行器'), ('sql_query', 'SQL查询'), ('api_call', 'API调用'), ('custom', '自定义工具')], max_length=50, verbose_name='工具类型')),
                ('tool_class', models.CharField(max_length=255, verbose_name='工具类名')),
                ('tool_config', models.JSONField(blank=True, default=dict, verbose_name='工具配置')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代理工具',
                'verbose_name_plural': '代理工具',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.UUIDField(verbose_name='代理ID')),
                ('conversation_id', models.IntegerField(blank=True, null=True, verbose_name='对话ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('memory_key', models.CharField(max_length=255, verbose_name='记忆键')),
                ('memory_data', models.JSONField(default=dict, verbose_name='记忆数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '代理记忆',
                'verbose_name_plural': '代理记忆',
                'ordering': ['-updated_at'],
                'unique_together': {('agent_id', 'conversation_id', 'memory_key')},
            },
        ),
    ]
