# Generated by Django 4.2.23 on 2025-07-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("key", models.CharField(max_length=64, unique=True, verbose_name="密钥")),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("last_used_at", models.DateTimeField(blank=True, null=True, verbose_name="最后使用时间")),
            ],
            options={
                "verbose_name": "API密钥",
                "verbose_name_plural": "API密钥",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField(unique=True, verbose_name="用户ID")),
                ("language_preference", models.CharField(default="zh-cn", max_length=10, verbose_name="语言偏好")),
                ("theme_preference", models.CharField(default="light", max_length=10, verbose_name="主题偏好")),
                ("monthly_quota", models.IntegerField(default=100, verbose_name="月度配额")),
                ("used_quota", models.IntegerField(default=0, verbose_name="已使用配额")),
                ("organization", models.CharField(blank=True, max_length=100, null=True, verbose_name="组织")),
                ("department", models.CharField(blank=True, max_length=100, null=True, verbose_name="部门")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "用户配置",
                "verbose_name_plural": "用户配置",
            },
        ),
    ]
