# Generated by Django 5.2.4 on 2025-08-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationMemoryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "conversation_id",
                    models.IntegerField(db_index=True, help_text="对话ID", verbose_name="对话ID"),
                ),
                (
                    "memory_type",
                    models.CharField(help_text="记忆类型", max_length=50, verbose_name="记忆类型"),
                ),
                (
                    "memory_data",
                    models.TextField(help_text="序列化的记忆数据", verbose_name="记忆数据"),
                ),
                (
                    "config_data",
                    models.JSONField(default=dict, help_text="记忆配置参数", verbose_name="配置数据"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间", verbose_name="最后更新时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间", verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "对话记忆状态",
                "verbose_name_plural": "对话记忆状态",
                "ordering": ["-last_updated"],
                "unique_together": {("conversation_id", "memory_type")},
            },
        ),
    ]
