# Generated by Django 5.2.4 on 2025-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qa", "0002_conversationmemorystate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConversationMemoryState",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
