# Generated by Django 4.2.23 on 2025-07-09 02:55

from django.db import migrations, models
import documents.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('file', models.FileField(upload_to=documents.models.models.document_file_path, verbose_name='文件')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF文档'), ('docx', 'Word文档'), ('txt', '文本文档')], max_length=10, verbose_name='文件类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('owner_id', models.IntegerField(verbose_name='用户ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('processed', '已处理'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(verbose_name='文档ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('chunk_index', models.IntegerField(verbose_name='块索引')),
                ('vector_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='向量ID')),
            ],
            options={
                'verbose_name': '文档块',
                'verbose_name_plural': '文档块',
                'ordering': ['document_id', 'chunk_index'],
                'unique_together': {('document_id', 'chunk_index')},
            },
        ),
    ]
