# Generated by Django 5.2.4 on 2025-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
