# Generated by Django 6.0.3 on 2026-03-30 14:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_add_soft_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=100, verbose_name='索引词')),
                ('chunk_id', models.IntegerField(db_index=True, verbose_name='块ID')),
                ('frequency', models.IntegerField(default=1, verbose_name='词频')),
                ('positions', models.TextField(blank=True, null=True, verbose_name='词位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '倒排索引',
                'verbose_name_plural': '倒排索引',
            },
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='vector_id',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_category',
            field=models.CharField(choices=[('user', '用户文档'), ('internal', '内部文档')], default='user', max_length=20, verbose_name='文档分类'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, db_index=True, dimensions=768, null=True, verbose_name='嵌入向量'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='hierarchy_level',
            field=models.IntegerField(default=0, verbose_name='层级'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='intent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='意图'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='keywords',
            field=models.TextField(blank=True, null=True, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='parent_chunk_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='父块索引'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='章节路径'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='标题/章节名'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['doc_category', 'status'], name='documents_d_doc_cat_d1546e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner_id', 'doc_category'], name='documents_d_owner_i_7900f4_idx'),
        ),
        migrations.AddIndex(
            model_name='invertedindex',
            index=models.Index(fields=['term'], name='idx_term'),
        ),
        migrations.AddIndex(
            model_name='invertedindex',
            index=models.Index(fields=['chunk_id'], name='idx_chunk_id'),
        ),
        migrations.AddIndex(
            model_name='invertedindex',
            index=models.Index(fields=['term', 'frequency'], name='idx_term_freq'),
        ),
        migrations.AlterUniqueTogether(
            name='invertedindex',
            unique_together={('term', 'chunk_id')},
        ),
    ]
